# Generated by Django 4.2.2 on 2023-06-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='chocies',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='enrollment',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
